"""Digest, streaming and freshness constants — all sourced from the canonical
registry (``app.constants``), R1: "the banned list lives in constants.py, and
[every] check imports it. There is one list, not two." The same rule applies to
every other numeric constant, not only the banned-copy list.

This module exists only to give the analytics/streaming subpackages a shorter,
domain-scoped import path; it defines no independent values.
"""

from app.constants import (
    BENCHMARK_ANCHOR_SYMBOL,
    CONFLATION_INTERVAL_MS,
    DECAY_TAU_SESSIONS,
    FRESHNESS_ANCHOR_SILENCE_MS,
    FRESHNESS_FLOW_MAX_AGE_MS,
    FRESHNESS_LIVE_MAX_AGE_MS,
    FRESHNESS_THIN_SILENCE_MS,
    STREAM_CLAIM_MIN_IDLE_TIME_MS,
    STREAM_CONSUMER_BATCH_SIZE,
    STREAM_CONSUMER_BLOCK_MS,
    STREAM_MAX_DELIVERY_ATTEMPTS,
    STREAM_TICKS_DLQ_KEY,
    STREAM_TICKS_KEY,
    STREAM_TICKS_MAXLEN,
    W_DELIVERY,
    W_EXTREME,
    W_SCAR,
    W_TURNOVER,
    WS_HEARTBEAT_INTERVAL_S,
    WS_MAX_SUBSCRIPTIONS_PER_CONN,
    WS_QUEUE_MAX,
    WS_SLOW_CLIENT_TIMEOUT_S,
)

WEIGHT_SAR: float = W_SCAR
WEIGHT_TURNOVER_Z: float = W_TURNOVER
WEIGHT_DELIVERY_Z: float = W_DELIVERY
WEIGHT_EXTREME: float = W_EXTREME
RECENCY_DECAY_TAU_SESSIONS: float = DECAY_TAU_SESSIONS

BOOST_HELD: float = 1.0
BOOST_PINNED: float = 1.0
BOOST_RECENTLY_ADDED: float = 0.5
BOOST_LEVEL_CROSSED: float = 1.4

MAX_ITEMS_PER_SECTOR: int = 3
SECTOR_DIVERSITY_SAR_OVERRIDE: float = 4.0

__all__ = [
    "BENCHMARK_ANCHOR_SYMBOL",
    "FRESHNESS_ANCHOR_SILENCE_MS",
    "FRESHNESS_FLOW_MAX_AGE_MS",
    "FRESHNESS_LIVE_MAX_AGE_MS",
    "FRESHNESS_THIN_SILENCE_MS",
    "STREAM_CLAIM_MIN_IDLE_TIME_MS",
    "STREAM_CONSUMER_BATCH_SIZE",
    "STREAM_CONSUMER_BLOCK_MS",
    "STREAM_MAX_DELIVERY_ATTEMPTS",
    "STREAM_TICKS_DLQ_KEY",
    "STREAM_TICKS_KEY",
    "STREAM_TICKS_MAXLEN",
    "WS_CONFLATION_INTERVAL_MS",
    "WS_CLIENT_OUTBOUND_QUEUE_MAXSIZE",
    "WS_SLOW_CLIENT_TIMEOUT_SECONDS",
    "WS_MAX_SUBSCRIPTIONS_PER_CLIENT",
    "WS_HEARTBEAT_INTERVAL_SECONDS",
    "WEIGHT_SAR",
    "WEIGHT_TURNOVER_Z",
    "WEIGHT_DELIVERY_Z",
    "WEIGHT_EXTREME",
    "RECENCY_DECAY_TAU_SESSIONS",
    "BOOST_HELD",
    "BOOST_PINNED",
    "BOOST_RECENTLY_ADDED",
    "BOOST_LEVEL_CROSSED",
    "MAX_ITEMS_PER_SECTOR",
    "SECTOR_DIVERSITY_SAR_OVERRIDE",
]

# Renamed aliases kept for the existing import paths in streaming/ and api/ws.py.
WS_CONFLATION_INTERVAL_MS = CONFLATION_INTERVAL_MS
WS_CLIENT_OUTBOUND_QUEUE_MAXSIZE = WS_QUEUE_MAX
WS_SLOW_CLIENT_TIMEOUT_SECONDS = WS_SLOW_CLIENT_TIMEOUT_S
WS_MAX_SUBSCRIPTIONS_PER_CLIENT = WS_MAX_SUBSCRIPTIONS_PER_CONN
WS_HEARTBEAT_INTERVAL_SECONDS = WS_HEARTBEAT_INTERVAL_S
