import { Register } from "../lib/register.jsx";
import Num from "../components/Num.jsx";

const sources = [["NSE cash bhavcopy", "06 Sep 18:31 IST", 1842], ["NSE corporate actions", "06 Sep 18:30 IST", 36], ["NIFTY index snapshot", "06 Sep 09:30 IST", 1], ["Exchange filings", "06 Sep 18:29 IST", 94]];

export default function Settings() {
  return <Register value="terminal"><section className="mx-auto w-full max-w-[1000px] space-y-10 px-6 py-8"><header className="border-b border-hairline pb-5"><p className="text-micro uppercase tracking-[0.18em] text-slate">Settings</p><h1 className="mt-2 text-display text-chalk">Reading controls</h1></header><section className="max-w-[640px] space-y-6"><div className="border-b border-hairline pb-5"><h2 className="text-section text-chalk">Cursor</h2><p className="mt-2 text-ui text-slate">The cursor sets the market session used for your change period.</p><button type="button" className="mt-4 rounded-[3px] border border-hairline px-4 py-2 text-ui text-chalk">Keep the current session</button></div><div className="border-b border-hairline pb-5"><h2 className="text-section text-chalk">Attention safety control</h2><p className="mt-2 text-ui text-slate">The item cap keeps the register small enough to read. It is a safety limit, not a cosmetic preference.</p><label className="mt-4 flex items-center gap-3 text-ui text-slate">Items per brief <select className="rounded-[3px] border border-hairline bg-panel px-3 py-2 text-chalk" defaultValue="4"><option value="4">4</option><option value="6">6</option><option value="8">8</option></select></label></div></section><section><h2 className="text-section text-chalk">Data provenance</h2><div className="mt-4 overflow-x-auto"><table className="w-full border-collapse text-ui"><thead className="border-b border-hairline text-left text-micro uppercase text-slate"><tr><th className="py-3">Source</th><th className="py-3">Last ingest</th><th className="py-3">Rows</th></tr></thead><tbody>{sources.map(([source, time, rows]) => <tr key={source} className="border-b border-hairline"><td className="py-3 text-chalk">{source}</td><td className="num py-3 text-slate">{time}</td><td className="py-3"><Num value={rows} /></td></tr>)}</tbody></table></div></section></section></Register>;
}

