"""Parser coverage report — BUILD_PLAN task 1.6.

    python -m app.ingest.coverage
    python -m app.ingest.coverage --no-readme

§5.3.0's whole argument for this file: "Regex will not extract everything, and
the design does not need it to. What it needs is to *know when it failed*.
Coverage is reported as a metric, not assumed." Silence about a parser's limits
invites a jury to find them; a report that says "94% and here is the other 6%"
does not.

Two independent pipelines are summarised, because they carry very different
stakes (§5.3.0's own table): corporate-action purpose strings are the one
High-risk text parse in the system, and announcement subjects are Low-risk —
a wrong category costs a ranking multiplier, never a phantom price.

─── The four CA buckets ──────────────────────────────────────────────────────

`corporate_actions.verification` carries five values across three tasks —
1.3 parses, 1.4 verifies against the market, 1.5 infers the unparsed tail — and
this report partitions them into the four BUILD_PLAN 1.6 asks for:

    parsed      VERIFIED + UNVERIFIED   the text produced a usable factor,
                                         whether or not the market has checked
                                         it yet
    discrepant  DISCREPANCY             the text produced a factor and the
                                         market contradicted it
    inferred    INFERRED                the text failed; the ex-date gap
                                         recovered a factor anyway
    unparsed    UNPARSED                neither the text nor the gap yielded
                                         one; the window is suppressed

These four are a partition of the verification enum by construction, so they
sum to the row count unconditionally — the task's stated acceptance criterion
holds by the shape of the query, not by anything that could drift out of sync
with it.

─── Announcements: not yet ingested ─────────────────────────────────────────

BUILD_PLAN task 2.8 — the announcement poller, its content-hash dedup, and the
historical backfill — has not run. `app.ingest.announcements.resolve_category`
exists (the §9.2 regex table, copied verbatim) so this report has something to
categorise announcements *with*, but there is nothing in the `announcements`
table yet to categorise. Reporting a confident 0/0/0 would be indistinguishable
from a working pipeline that measured zero coverage; this report says which one
it is.
"""

from __future__ import annotations

import argparse
import logging
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

import sqlalchemy as sa

from app.db import get_engine
from app.ingest import announcements as ann
from app.ingest import ca_verify

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[3]
README_PATH = REPO_ROOT / "README.md"

# Bucket names, fixed so the printed report, the README section and the tests
# all use one vocabulary.
PARSED = "parsed"
INFERRED = "inferred"
UNPARSED = "unparsed"
DISCREPANT = "discrepant"
CA_BUCKETS = (PARSED, INFERRED, UNPARSED, DISCREPANT)

# How many distinct unparsed strings to print — enough to be a real answer to
# "here is the list", not so many the report stops being readable.
EXAMPLE_LIMIT = 15

README_START = "<!-- COVERAGE:START — generated by `python -m app.ingest.coverage` -->"
README_END = "<!-- COVERAGE:END -->"


@dataclass(frozen=True)
class UnparsedExample:
    """One distinct unparsed purpose string, and how often it recurs."""

    purpose_raw: str
    count: int
    sample_symbol: str
    sample_ex_date: str


@dataclass
class CACoverage:
    """The four-bucket partition of `corporate_actions.verification`."""

    total: int = 0
    buckets: Counter[str] = field(default_factory=Counter)
    # Sub-detail within "parsed" — not part of the four-bucket sum, purely
    # informational: how much of "parsed" the market has actually settled yet.
    verified: int = 0
    unverified: int = 0
    examples: list[UnparsedExample] = field(default_factory=list)

    @property
    def coverage_ratio(self) -> float:
        """The share that ended up with a usable factor, one way or the other.

        This is the number §5.3.0's "our parser covers 94%" line is about:
        parsed and inferred rows can be applied to a price series; discrepant
        and unparsed rows are suppressed under §5.3's fail-safe rule.
        """
        if not self.total:
            return 0.0
        return (self.buckets[PARSED] + self.buckets[INFERRED]) / self.total

    def render(self) -> str:
        lines = [
            f"Corporate actions: {self.total} rows",
            "",
        ]
        for bucket in CA_BUCKETS:
            count = self.buckets[bucket]
            share = count / self.total if self.total else 0.0
            lines.append(f"  {bucket:11s} {count:5d}  {share:6.1%}")
        lines.append("")
        lines.append(f"  coverage (parsed + inferred) : {self.coverage_ratio:.1%}")
        lines.append(
            f"  of which parsed is VERIFIED {self.verified} / UNVERIFIED {self.unverified}"
        )
        if self.examples:
            lines.append("")
            lines.append(
                f"  {len(self.examples)} distinct unparsed strings shown "
                f"(of {self.buckets[UNPARSED]} rows):"
            )
            for example in self.examples:
                lines.append(
                    f"    x{example.count:<3d} {example.purpose_raw[:70]!r} "
                    f"(e.g. {example.sample_symbol} {example.sample_ex_date})"
                )
        return "\n".join(lines)


@dataclass
class AnnouncementCoverage:
    """Announcement subjects grouped by which §9.2 step categorised them."""

    total: int = 0
    by_desc: int = 0
    by_regex: int = 0
    other: int = 0
    ingested: bool = False

    def render(self) -> str:
        if not self.ingested:
            return (
                "Announcements: 0 rows — not yet ingested.\n"
                "  BUILD_PLAN task 2.8 polls the NSE corporate-announcements\n"
                "  endpoint and backfills the same history window as the\n"
                "  bhavcopy. `app.ingest.announcements.resolve_category`\n"
                "  already implements the §9.2 resolution order and will\n"
                "  categorise every row this report shows 0 for today."
            )
        lines = [f"Announcements: {self.total} rows", ""]
        for label, count in (
            ("resolved by desc", self.by_desc),
            ("resolved by regex", self.by_regex),
            ("as OTHER", self.other),
        ):
            share = count / self.total if self.total else 0.0
            lines.append(f"  {label:18s} {count:5d}  {share:6.1%}")
        return "\n".join(lines)


def ca_coverage(conn: sa.Connection, *, example_limit: int = EXAMPLE_LIMIT) -> CACoverage:
    """Tally `corporate_actions.verification` into the four §1.6 buckets."""
    report = CACoverage()
    rows = conn.execute(
        sa.text("SELECT verification, COUNT(*) FROM corporate_actions GROUP BY 1")
    ).all()
    counts = {str(verification): int(count) for verification, count in rows}
    report.total = sum(counts.values())
    report.verified = counts.get(ca_verify.VERIFIED, 0)
    report.unverified = counts.get(ca_verify.UNVERIFIED, 0)
    report.buckets = Counter(
        {
            PARSED: report.verified + report.unverified,
            INFERRED: counts.get(ca_verify.INFERRED, 0),
            UNPARSED: counts.get(ca_verify.UNPARSED, 0),
            DISCREPANT: counts.get(ca_verify.DISCREPANCY, 0),
        }
    )

    if report.buckets[UNPARSED]:
        example_rows = conn.execute(
            sa.text(
                """
                SELECT purpose_raw, COUNT(*) AS n,
                       (array_agg(symbol ORDER BY ex_date DESC))[1] AS symbol,
                       (array_agg(ex_date ORDER BY ex_date DESC))[1] AS ex_date
                FROM corporate_actions
                WHERE verification = 'UNPARSED'
                GROUP BY purpose_raw
                ORDER BY n DESC, purpose_raw
                LIMIT :limit
                """
            ),
            {"limit": example_limit},
        ).all()
        report.examples = [
            UnparsedExample(purpose_raw, count, symbol, ex_date.isoformat())
            for purpose_raw, count, symbol, ex_date in example_rows
        ]
    return report


def announcement_coverage(conn: sa.Connection) -> AnnouncementCoverage:
    """Categorise every announcement and tally which §9.2 step answered.

    Reads `raw_json->>'desc'` rather than a hypothetical `desc` column: §9.1's
    schema stores the exchange's payload verbatim in `raw_json` and only
    derives `category` from it, so `desc` is reached the same way the real
    ingest (task 2.8) will reach it.
    """
    total = conn.execute(sa.text("SELECT COUNT(*) FROM announcements")).scalar_one()
    if not total:
        return AnnouncementCoverage(total=0, ingested=False)

    tally: Counter[str] = Counter()
    rows = conn.execute(
        sa.text("SELECT raw_json->>'desc' AS desc, subject FROM announcements")
    )
    for desc, subject in rows:
        resolution = ann.resolve_category(desc=desc, subject=subject)
        tally[resolution.source] += 1

    return AnnouncementCoverage(
        total=total,
        by_desc=tally[ann.FROM_DESC],
        by_regex=tally[ann.FROM_REGEX],
        other=tally[ann.FROM_OTHER],
        ingested=True,
    )


def render_report(ca: CACoverage, announcements: AnnouncementCoverage) -> str:
    return (
        "Parser coverage report — BUILD_PLAN task 1.6\n"
        f"{'=' * 60}\n\n"
        f"{ca.render()}\n\n"
        f"{announcements.render()}\n"
    )


def render_readme_section(ca: CACoverage, announcements: AnnouncementCoverage) -> str:
    """A compact Markdown table for the README, distinct from the CLI's prose.

    §5.3.0's argument is aimed at a reader deciding whether to trust the
    product, so the README states the coverage ratio and the honest caveat
    about announcements in the first two lines rather than making a reader
    find them in a wall of numbers.
    """
    lines = [
        README_START,
        "### Parser coverage",
        "",
        f"Corporate-action purpose strings: **{ca.coverage_ratio:.1%}** "
        f"produced a usable factor ({ca.total} rows in the backfilled history).",
        "",
        "| | rows | share |",
        "|---|---:|---:|",
    ]
    for bucket in CA_BUCKETS:
        count = ca.buckets[bucket]
        share = count / ca.total if ca.total else 0.0
        lines.append(f"| {bucket} | {count} | {share:.1%} |")
    lines.append("")
    if ca.examples:
        lines.append(
            f"<details><summary>{ca.buckets[UNPARSED]} unparsed rows across "
            f"{len(ca.examples)} distinct strings</summary>\n"
        )
        lines.append("| purpose string | rows | example |")
        lines.append("|---|---:|---|")
        for example in ca.examples:
            escaped = example.purpose_raw.replace("|", "\\|")
            lines.append(
                f"| {escaped} | {example.count} | "
                f"{example.sample_symbol} {example.sample_ex_date} |"
            )
        lines.append("\n</details>")
        lines.append("")
    if announcements.ingested:
        lines += [
            f"Announcements: **{announcements.total}** filings — "
            f"{announcements.by_desc} resolved by the exchange's own `desc` "
            f"field, {announcements.by_regex} by the subject-line regex "
            f"fallback, {announcements.other} as `OTHER`.",
        ]
    else:
        lines += [
            "Announcements: not yet ingested — BUILD_PLAN task 2.8. The "
            "category resolver (`app.ingest.announcements.resolve_category`, "
            "§9.2) is implemented and ready to categorise them once that "
            "task's backfill runs.",
        ]
    lines.append("")
    lines.append(README_END)
    return "\n".join(lines)


def update_readme(section: str, *, path: Path = README_PATH) -> None:
    """Write or replace the coverage section, leaving the rest of the file —
    if any — untouched.

    README.md does not exist yet (BUILD_PLAN task 14.1 writes the full
    document); this creates a minimal one so the coverage numbers have
    somewhere to live now, in the same place 14.1 will build around.
    """
    if not path.exists():
        path.write_text(
            "# Smart Market Watchlist\n\n"
            "The full README (thesis, evidence, business case, data "
            "provenance, setup) lands with BUILD_PLAN task 14.1. This file "
            "exists ahead of that so the parser coverage numbers task 1.6 "
            "requires have somewhere to live.\n\n"
            f"{section}\n",
            encoding="utf-8",
        )
        log.info("created %s with the coverage section", path)
        return

    text = path.read_text(encoding="utf-8")
    if README_START in text and README_END in text:
        before, _, rest = text.partition(README_START)
        _, _, after = rest.partition(README_END)
        text = before + section + after
    else:
        # An existing README with no coverage markers yet — append, so a
        # human-written file (or task 14.1's fuller one) is never truncated.
        text = text.rstrip("\n") + "\n\n" + section + "\n"
    path.write_text(text, encoding="utf-8")
    log.info("updated the coverage section in %s", path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-readme", action="store_true", help="Print the report; do not touch README.md."
    )
    parser.add_argument("--readme-path", type=Path, default=README_PATH)
    parser.add_argument(
        "--example-limit",
        type=int,
        default=EXAMPLE_LIMIT,
        help="Distinct unparsed strings to list.",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)-7s %(message)s")

    engine = get_engine()
    with engine.connect() as conn:
        ca = ca_coverage(conn, example_limit=args.example_limit)
        announcements = announcement_coverage(conn)

    print(render_report(ca, announcements))

    if not args.no_readme:
        update_readme(render_readme_section(ca, announcements), path=args.readme_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
